### ISSUE TITLE
[MCU_Op] RAM usage still broken.

### ISSUE THREAD

**Issue by PonyFlare** [PrimeSonic/PrimeSonicSubnauticaMods#24]
As  I talked about on Nexus, this mod was causing the game to take all the RAM available and fail to load. This update hasn't fixed anything in that regard.

**Comment by PrimeSonic** [comment]
After multiple unsuccessful attempts to reproduce the issue, I can only conclude that there is something else on this user's PC that is causing the game to behave this way.   

Even after consecutive hours of play, with several Auxiliary Upgrade Consoles and multiple upgrade modules of all types in them, I saw no climb in system memory usage.  

Another user that reported memory leaks was also unable to reproduce this error once they started testing on a new save file.
https://www.nexusmods.com/subnautica/mods/101/?tab=posts&jump_to_comment=63088646
I used my oldest save file during my own testing which had my fully loaded Cyclops.

Without access to the reporting user's PC to evaluate what other software may be interacting with the game, there is nothing more I can do to diagnose this issue.  
And having fully reviewed the code in detail for any possible oversight which might be more memory hungry than necessary, I do not believe that this mod is the actual cause of the symptoms the reporting user is experiencing.

The source code is publicly available, should any user wish to review it in search of potential issues.
https://github.com/PrimeSonic/PrimeSonicSubnauticaMods/tree/master/MoreCyclopsUpgrades
