### ISSUE TITLE
Seamoth Torpedo System Module is not supported

### ISSUE THREAD

**Issue by Mavoc** [PrimeSonic/PrimeSonicSubnauticaMods#34]
The Vehicle Module Fabricator does not support crafting the Seamoth's Torpedo System Module. Skimming through the code, the SeamothTorpedoModule techtype does not appear to be present anywhere.  I attempted to add the module to the ModdedItemsConfig.txt file in an attempt to work around the issue, but it did not succeed.

I am able to build the module through the crafting station in a moonpool.

**Comment by PrimeSonic** [comment]
Resolved in 2.1.1 d4e664ad8b56f904e8dd625af07b08ce250ed4fe
