### ISSUE TITLE
Add Animation to CyBioReactor to show it is active an has bio mass to consume

### ISSUE THREAD

**Issue by leonard84** [PrimeSonic/PrimeSonicSubnauticaMods#56]
Currently you can't really tell if the BioReactor has contents unless inspecting it.

I think it would be cool if you could just let the added components swim around in it.

**Comment by leonard84** [comment]
![Seeds](https://user-images.githubusercontent.com/1151511/55597385-96772600-574d-11e9-94a2-b27f807e16b5.jpg)

**Comment by PrimeSonic** [comment]
I'm afraid that's not within my current skill set to do.  
If I could have made the CyBioReactor more animated from the get-go, I would have already.

You're more than welcome to offer code snippets or an outright Pull Request if you have a way to do this.  
You will be credited accordingly and offered a portion of the Donation Points from downloads of the mod.

For right now, the only thing I know I will be attempting to do for the CyBioReactor is attempting to get some outwardly visible text on it to serve a similar function to the power indicator icons.  
But if you can do one better, I'm always willing to collaborate.

**Comment by leonard84** [comment]
I'm sorry I have no experience with modding Subnautica, maybe you could adapt the display technology from https://github.com/brett-taylor/SubnauticaResourceMonitorMod to display the contents on the outside monitor.

**Comment by PrimeSonic** [comment]
I'm afraid I will have to close this issue then, since there's really nothing functionally wrong here.

I was already planning on making another visual update to the Cyclops BioReactor.  
It's simply that graphical changes like that take a lot of time to do with a ton of trial and error to get right.  
So when I can devote time to that, I will.
